substitutions:
  name: "seeed-ir"
  friendly_name: "Panasonic AC Controller"
  version: "v1"

esphome:
  name: xiao-ir-ac-controller
  friendly_name: Xiao-IR-AC-Controller

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino

external_components:
  - source:
      type: git
      url: https://github.com/mistic100/ESPHome-IRremoteESP8266
    components: [ ir_remote_base, panasonic ]

globals:
  - id: reset_press_time
    type: uint32_t
    initial_value: '0'
  - id: touch_count
    type: int
    restore_value: no
    initial_value: '0'
  - id: touch_timer
    type: unsigned long
    restore_value: no
    initial_value: '0'

logger:
  level: INFO

api:
  encryption:
    key: "U/lyvWTpxGBxJstAPb2MZ0oY4I8azHqD4S8XmZFBKsU="

ota:
  - platform: esphome
    password: "574f7f59310160a8efde98f3b2984b3d"

wifi:
  ssid: "Harbour Point"
  password: "chiangmai"
  ap:
    password: "12345678"

captive_portal:

remote_transmitter:
  id: default_ir_transmitter
  pin: GPIO3
  carrier_duty_percent: 50%
  non_blocking: true
  # rmt_symbols: 96        # full TX RMT pool for IR

remote_receiver:
  id: default_ir_receiver
  pin:
    number: GPIO4
    inverted: true
  #rmt_symbols: 48
  dump: raw

climate:
  - platform: panasonic
    name: "Panasonic Air Conditioner"
    id: panasonic_ac
    model: DKE                  # change if your Panasonic model differs
    transmitter_id: default_ir_transmitter
    supports_cool: true
    supports_heat: false        # set true if your unit supports heat

# Simple IR test button to verify IR output with a phone camera
# button:
#   - platform: template
#     name: "IR Test Burst"
#     on_press:
#       - remote_transmitter.transmit_raw:
#           carrier_frequency: 38000 Hz
#           code: [9000, -4500, 560, -560, 560, -560, 560, -1690]
#           repeat:
#             times: 5
#             wait_time: 10ms

button:
  - platform: template
    name: "Panasonic ON/OFF (raw)"
    id: panasonic_onoff_raw
    on_press:
      - remote_transmitter.transmit_raw:
          carrier_frequency: 38000 Hz
          code:
            - 3564
            - -1703
            - 421
            - -453
            - 419
            - -1326
            - 419
            - -454
            - 419
            - -454
            - 419
            - -453
            - 419
            - -454
            - 419
            - -455
            - 419
            - -454
            - 419
            - -453
            - 420
            - -453
            - 419
            - -454
            - 418
            - -455
            - 418
            - -454
            - 419
            - -1327
            - 419
            - -454
            - 419
            - -454
            - 419
            - -454
            - 419
            - -453
            - 420
            - -453
            - 418
            - -455
            - 418
            - -454
            - 419
            - -1327
            - 418
            - -1327
            - 419
            - -1328
            - 419
            - -454
            - 419
            - -453
            - 419
            - -1327
            - 418
            - -454
            - 419
            - -454
            - 419
            - -454
            - 419
            - -454
            - 419
            - -454
            - 419
            - -454
            - 418
            - -454
            - 419
            - -454
            - 418
            - -455
            - 418
            - -455
            - 418
            - -454
            - 419
            - -454
            - 419
            - -455
            - 419
            - -454
            - 418
            - -454
            - 419
            - -455
            - 418
            - -454
            - 441
            - -432
            - 418
            - -455
            - 419
            - -454
            - 442
            - -431
            - 418
            - -454
            - 418
            - -455
            - 418
            - -454
            - 419
            - -455
            - 442
            - -431
            - 421
            - -451
            - 443
            - -430
            - 442
            - -432
            - 417
            - -456
            - 417
            - -1328
            - 442
            - -1303
            - 442
            - -431
            - 442
            - -431
            - 441
            - -432
            - 418
            - -455
            - 442
            - -431
            - 442
            - -9990
            - 3530
            - -1710
            - 441
            - -432
            - 418
            - -1330
            - 441
            - -431
            - 442
            - -432
            - 442
            - -431
            - 442
            - -432
            - 442
            - -432
            - 441
            - -434
            - 441
            - -432
            - 442
            - -432
            - 441
            - -432
            - 441
            - -432
            - 442
            - -432
            - 440
            - -1307
            - 441
            - -433
            - 440
            - -434
            - 442
            - -432
            - 442
            - -432
            - 441
            - -432
            - 440
            - -433
            - 441
            - -433
            - 440
            - -1306
            - 442
            - -1305
            - 442
            - -1306
            - 440
            - -432
            - 442
            - -432
            - 441
            - -1330
            - 417
            - -432
            - 440
            - -434
            - 440
            - -433
            - 441
            - -457
            - 416
            - -434
            - 440
            - -434
            - 440
            - -457
            - 417
            - -456
            - 417
            - -433
            - 440
            - -433
            - 441
            - -457
            - 416
            - -433
            - 441
            - -458
            - 417
            - -1330
            - 417
            - -456
            - 416
            - -1330
            - 417
            - -1330
            - 416
            - -1330
            - 417
            - -1329
            - 417
            - -457
            - 417
            - -458
            - 417
            - -1329
            - 417
            - -457
            - 416
            - -457
            - 417
            - -457
            - 417
            - -1330
            - 417
            - -1330
            - 416
            - -457
            - 416
            - -458
            - 417
            - -457
            - 416
            - -457
            - 417
            - -456
            - 417
            - -457
            - 416
            - -457
            - 416
            - -457
            - 417
            - -457
            - 417
            - -1331
            - 416
            - -1330
            - 416
            - -1332
            - 415
            - -1331
            - 415
            - -1331
            - 416
            - -457
            - 416
            - -1331
            - 416
            - -458
            - 416
            - -1331
            - 415
            - -1331
            - 416
            - -457
            - 417
            - -1330
            - 416
            - -1331
            - 416
            - -458
            - 415
            - -459
            - 416
            - -457
            - 417
            - -458
            - 417
            - -456
            - 417
            - -456
            - 418
            - -456
            - 417
            - -456
            - 417
            - -457
            - 417
            - -456
            - 418
            - -456
            - 418
            - -457
            - 417
            - -456
            - 417
            - -1330
            - 416
            - -1329
            - 418
            - -1330
            - 416
            - -458
            - 416
            - -457
            - 417
            - -457
            - 417
            - -457
            - 417
            - -456
            - 417
            - -457
            - 416
            - -458
            - 416
            - -457
            - 417
            - -457
            - 416
            - -1331
            - 416
            - -1330
            - 393
            - -1354
            - 393
            - -481
            - 392
            - -481
            - 392
            - -481
            - 393
            - -481
            - 392
            - -481
            - 392
            - -482
            - 392
            - -482
            - 392
            - -483
            - 391
            - -482
            - 391
            - -483
            - 391
            - -481
            - 393
            - -481
            - 392
            - -481
            - 392
            - -482
            - 392
            - -482
            - 392
            - -482
            - 392
            - -1355
            - 392
            - -481
            - 392
            - -482
            - 392
            - -1355
            - 391
            - -482


binary_sensor:
  - platform: gpio
    id: touch_pad
    pin:
      number: GPIO5
      mode: INPUT_PULLDOWN
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: touch_pad
            then:
              - script.execute: vibe_short
              - lambda: |-
                  unsigned long current_time = millis();
                  if (current_time - id(touch_timer) < 300) {
                    id(touch_count)++;
                  } else {
                    id(touch_count) = 1;
                  }
                  id(touch_timer) = current_time;
                  ESP_LOGD("touch_pad", "Touch detected. Current count: %d", id(touch_count));
                  if (id(check_touch_actions_script).is_running()) {
                    id(check_touch_actions_script).stop();
                  }
                  id(check_touch_actions_script).execute();

  - platform: gpio
    id: reset_button
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
    filters:
      - invert
    on_press:
      then:
        - lambda: id(reset_press_time) = millis();
    on_release:
      then:
        - lambda: |-
            uint32_t press_duration = millis() - id(reset_press_time);
            if (press_duration < 5000) {
              id(vibe_short).execute();
              ESP_LOGI("reset_button", "Short press: Restarting device.");
              ESP.restart();
            } else {
              id(vibe_long).execute();
              ESP_LOGI("reset_button", "Long press: Activating factory reset.");
              id(factory_reset_switch).turn_on();
            }

output:
  - platform: gpio
    id: vibration_output
    pin: GPIO6

switch:
  - platform: output
    id: vibration_switch
    name: "Vibration Motor"
    output: vibration_output
  - platform: factory_reset
    id: factory_reset_switch
    name: "Factory Reset"

script:
  - id: vibe_short
    then:
      - switch.turn_on: vibration_switch
      - delay: 100ms
      - switch.turn_off: vibration_switch

  - id: vibe_long
    then:
      - switch.turn_on: vibration_switch
      - delay: 500ms
      - switch.turn_off: vibration_switch

  - id: check_touch_actions_script
    mode: restart
    then:
      - delay: 350ms
      - if:
          condition:
            lambda: 'return id(touch_count) == 1;'
          then:
            - logger.log: "Single Click: Toggling Panasonic AC Power"
            - lambda: |-
                if (id(panasonic_ac).mode == climate::CLIMATE_MODE_OFF) {
                  auto call = id(panasonic_ac).make_call();
                  call.set_mode(climate::CLIMATE_MODE_COOL);
                  call.set_target_temperature(25);
                  call.perform();
                } else {
                  auto call = id(panasonic_ac).make_call();
                  call.set_mode(climate::CLIMATE_MODE_OFF);
                  call.perform();
                }
          else:
            - if:
                condition:
                  lambda: 'return id(touch_count) == 2;'
                then:
                  - logger.log: "Double Click: Panasonic AC Temperature Up"
                  - lambda: |-
                      if (id(panasonic_ac).mode != climate::CLIMATE_MODE_OFF) {
                        float t = id(panasonic_ac).target_temperature;
                        float max_t = id(panasonic_ac).get_traits().get_visual_max_temperature();
                        if (t < max_t) {
                          auto call = id(panasonic_ac).make_call();
                          call.set_target_temperature(t + 1.0f);
                          call.perform();
                        }
                      }
                else:
                  - if:
                      condition:
                        lambda: 'return id(touch_count) == 3;'
                      then:
                        - logger.log: "Triple Click: Panasonic AC Temperature Down"
                        - lambda: |-
                            if (id(panasonic_ac).mode != climate::CLIMATE_MODE_OFF) {
                              float t = id(panasonic_ac).target_temperature;
                              float min_t = id(panasonic_ac).get_traits().get_visual_min_temperature();
                              if (t > min_t) {
                                auto call = id(panasonic_ac).make_call();
                                call.set_target_temperature(t - 1.0f);
                                call.perform();
                              }
                            }
                      else:
                        - logger.log:
                            level: WARN
                            format: "Touch Action: No specific action defined for %d clicks."
                            args: ['id(touch_count)']
      - lambda: 'id(touch_count) = 0;'
